C     Diagram 1, Amplitude 1
      DATA MAPCONFIG(   1)/   1/
      DATA (IFOREST(I, -1,   1),I=1,2)/  4,  3/
      DATA SPROP(  -1,   1)/       6/
      DATA (IFOREST(I, -2,   1),I=1,2)/  5, -1/
      DATA SPROP(  -2,   1)/      21/
C     Diagram 2, Amplitude 2
      DATA MAPCONFIG(   2)/   2/
      DATA (IFOREST(I, -1,   2),I=1,2)/  5,  3/
      DATA SPROP(  -1,   2)/      -6/
      DATA (IFOREST(I, -2,   2),I=1,2)/  4, -1/
      DATA SPROP(  -2,   2)/      21/
C     Number of configs
      DATA MAPCONFIG(0)/   2/
