C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (Identity(2,1)) + Coup(2) * (Gamma5(2,1))
C     
      SUBROUTINE FFS1_5_0(F1, F2, S3, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP2
      COMPLEX*16 S3(*)
      COMPLEX*16 COUP1
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP14
      COMPLEX*16 VERTEX
      COMPLEX*16 TMP16
      TMP14 = (F2(5)*F1(5)+F2(6)*F1(6)+F2(7)*F1(7)+F2(8)*F1(8))
      TMP16 = (F2(7)*F1(7)+F2(8)*F1(8)-F2(5)*F1(5)-F2(6)*F1(6))
      VERTEX = -S3(5)*(+CI*(TMP14*COUP1+TMP16*COUP2))
      END


