C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma5(2,1)
C     
      SUBROUTINE FFS5_0(F1, F2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 S3(*)
      COMPLEX*16 F1(*)
      COMPLEX*16 TMP16
      COMPLEX*16 F2(*)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      TMP16 = (F2(7)*F1(7)+F2(8)*F1(8)-F2(5)*F1(5)-F2(6)*F1(6))
      VERTEX = COUP*(-CI * TMP16*S3(5))
      END


