C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (Identity(2,1)) + Coup(2) * (Gamma5(2,1))
C     
      SUBROUTINE MP_FFS1_5_0(F1, F2, S3, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP2
      COMPLEX*32 S3(*)
      COMPLEX*32 COUP1
      COMPLEX*32 F1(*)
      COMPLEX*32 F2(*)
      COMPLEX*32 TMP14
      COMPLEX*32 VERTEX
      COMPLEX*32 TMP16
      TMP14 = (F2(5)*F1(5)+F2(6)*F1(6)+F2(7)*F1(7)+F2(8)*F1(8))
      TMP16 = (F2(7)*F1(7)+F2(8)*F1(8)-F2(5)*F1(5)-F2(6)*F1(6))
      VERTEX = -S3(5)*(+CI*(TMP14*COUP1+TMP16*COUP2))
      END


