ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of HC_NLO_X0_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'UV_3Gb = ', UV_3GB
      WRITE(*,2) 'UV_3Gt = ', UV_3GT
      WRITE(*,2) 'UV_GQQb = ', UV_GQQB
      WRITE(*,2) 'UV_GQQt = ', UV_GQQT
      WRITE(*,2) 'UV_tMass = ', UV_TMASS
      WRITE(*,2) 'UVWfct_t_0 = ', UVWFCT_T_0
      WRITE(*,2) 'UVWfct_G_2 = ', UVWFCT_G_2
      WRITE(*,2) 'UVWfct_G_1 = ', UVWFCT_G_1
      WRITE(*,2) 'UV_X0tt_h = ', UV_X0TT_H
      WRITE(*,2) 'UV_X0tt_a = ', UV_X0TT_A
      WRITE(*,2) 'R2_ttX0_h = ', R2_TTX0_H
      WRITE(*,2) 'R2_ttX0_a = ', R2_TTX0_A
      WRITE(*,2) 'R2_ggX0_hb = ', R2_GGX0_HB
      WRITE(*,2) 'R2_ggX0_ht = ', R2_GGX0_HT
      WRITE(*,2) 'UV_X0tt_h_1eps = ', UV_X0TT_H_1EPS
      WRITE(*,2) 'UV_X0tt_a_1eps = ', UV_X0TT_A_1EPS
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'R2_3Gq = ', R2_3GQ
      WRITE(*,2) 'R2_3Gg = ', R2_3GG
      WRITE(*,2) 'R2_GQQ = ', R2_GQQ
      WRITE(*,2) 'R2_GGq = ', R2_GGQ
      WRITE(*,2) 'R2_GGb = ', R2_GGB
      WRITE(*,2) 'R2_GGt = ', R2_GGT
      WRITE(*,2) 'R2_GGg_1 = ', R2_GGG_1
      WRITE(*,2) 'R2_GGg_2 = ', R2_GGG_2
      WRITE(*,2) 'R2_QQq = ', R2_QQQ
      WRITE(*,2) 'R2_QQt = ', R2_QQT
      WRITE(*,2) 'UV_3Gg_1eps = ', UV_3GG_1EPS
      WRITE(*,2) 'UV_3Gb_1eps = ', UV_3GB_1EPS
      WRITE(*,2) 'UV_GQQg_1eps = ', UV_GQQG_1EPS
      WRITE(*,2) 'UV_GQQq_1eps = ', UV_GQQQ_1EPS
      WRITE(*,2) 'UV_tMass_1eps = ', UV_TMASS_1EPS
      WRITE(*,2) 'UVWfct_b_0_1eps = ', UVWFCT_B_0_1EPS
      WRITE(*,2) 'UVWfct_G_2_1eps = ', UVWFCT_G_2_1EPS
      WRITE(*,2) 'GC_3009a = ', GC_3009A
      WRITE(*,2) 'GC_3009h = ', GC_3009H
      WRITE(*,2) 'GC_3010a = ', GC_3010A
      WRITE(*,2) 'GC_3010h = ', GC_3010H
